baseURL = 'https://vanleussen.com/'
languageCode = 'en-us'
title = 'Martins Website'
theme = "LoveIt"

googleAnalytics = "G-H2S04476CH"

[params]
    title = "Martins Website"
    [params.header]
        [params.header.title]
            name = "Martin's Website"
    [params.home]
        [params.home.profile]
            enable = true
            title = ""
            subtitle = "Martin van Leussen"
            avatarurl = "/Emoji.png"
        [params.home.posts]
            enable = "false"
    
    [params.social]
        Linkedin = "mvanleussen"
    [params.analytics]
        enable = true
        # Google Analytics
        [params.analytics.google]
            id = "G-H2S04476CH"
            # whether to anonymize IP
            anonymizeIP = true